services:

  app:
    build: .
    container_name: lightrees-app

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: postgresql://lightrees:password@postgres:5432/lightrees
      JWT_SECRET: production-secret-change-this

    depends_on:
      - postgres


  postgres:
    image: postgres:16

    container_name: lightrees-postgres

    environment:
      POSTGRES_USER: lightrees
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lightrees

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: